#!/usr/bin/env bash
set -e

make -C reconf/lib/dmalloc

cp reconf/lib/dmalloc/build/dmalloc.a reconf/
gcc -Ireconf/include -fno-builtin -o reconf/reconf reconf/src/*.c reconf/dmalloc.a

./reconf/reconf
./configure

ninja -C build
